//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Lab06.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define ID_INDICATOR_MOUSE              126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_Lab06TYPE                   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_TEXT                 310
#define IDR_POPMENU                     312
#define IDD_DIALOG_SIZE                 313
#define IDD_DIALOG_LOCATION             315
#define IDD_DIALOG_GETLENGTH            317
#define IDC_EDIT1                       1000
#define IDC_STATIC_Y                    1003
#define IDC_EDITY                       1004
#define IDC_STATIC_X2                   1005
#define IDC_EDIT_LOC_X                  1005
#define IDC_EDITX                       1006
#define IDC_EDIT_LOC_Y                  1006
#define IDC_EDIT_GETLEN                 1006
#define ID_DRAW_LINE                    32771
#define ID_DRAW_SELECT                  32772
#define ID_DRAW_RECT                    32773
#define ID_DRAW_ELLIPSE                 32777
#define ID_DRAW_TEXT                    32778
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_32783                        32783
#define ID_SETTINGS_LINECOLOR           32784
#define ID_SETTINGS_BRUSHCOLOR          32785
#define ID_SETTINGS_TEXTCOLOR           32786
#define ID_POPMENU_LINE_COLOR           32787
#define ID_32788                        32788
#define ID_                             32789
#define ID_POPMENU_RECT_COLOR           32790
#define ID_32791                        32791
#define ID_POPMENU_LINE_STYLE           32792
#define ID_LINE_STYLE_1                 32793
#define ID_POPMENU_TEXT_FONT            32794
#define ID_32795                        32795
#define ID_POPMENU_LINE_DELETE          32796
#define ID_POPMENU_RECT_DELETE          32797
#define ID_32798                        32798
#define ID_POPMENU_TEXT_CONTENT         32799
#define ID_POPMENU_RECT_SIZE            32800
#define ID_POPMENU_ELLP_LOCATION        32801
#define ID_32802                        32802
#define ID_POPMENU_LINE_CHANGESTART     32803
#define ID_32804                        32804
#define ID_POPMENU_LINE_CHANGELENGTH    32805
#define ID_32806                        32806
#define ID_POPMENU_RECT_LOCATION        32807
#define ID_32808                        32808
#define ID_LineStyle2                   32809
#define ID_LineStyle3                   32810
#define ID_32811                        32811
#define ID_RECTLINE_1                   32812
#define ID_RECTLINE_2                   32813
#define ID_RECTLINE_3                   32814
#define ID_POPMENU_TEXT_DELETE          32815
#define ID_POPMENU__DELETE              32816
#define ID_POPMENU_ELLP_DELETE          32817
#define ID_32818                        32818
#define ID_POPMENU_ELLP_COLOR           32819
#define ID_POPMENU_ELLP_SIZE            32820
#define ID_32821                        32821
#define ID_ELLP_LINE1                   32822
#define ID_ELLP_LINE2                   32823
#define ID_ELLP_LINE3                   32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        319
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
